### PR TITLE
Add cards for info and organizers

### LINKED ISSUE #6: Create a simple gallery section for listing organizers on the about page
Sections like [Organizers on the About page](https://socialjusticehackathon.github.io/website/about.html) contain of a gallery of people. Each item is a photo, along with a description.

This issue is to track generating sections like this by...

* Committing organizer data to the repo (e.g. organizers.csv, exported from a spreadsheet).
  - I've added an [about--organizers spreadsheet](https://docs.google.com/spreadsheets/d/1sBa7j4rwgNr0EFLa4sZ_8EugCDlmCxtRaMvTlOs_U-E/edit?usp=sharing) to the website folder on google drive
  - (Here is last year's [google doc](https://docs.google.com/document/d/1-n6zXTi285g1DTA9MHKsuffaHpEv_r6voqrR66sbqTg/edit?usp=sharing))
* Committing organizer photos to the repo.
* Generating a section using either code or a custom quarto gallery

## Option 1: using code

This approach is used in the [quartodoc example page](https://machow.github.io/quartodoc/examples/) ([source code](https://github.com/machow/quartodoc/blob/main/docs/examples/index.qmd))

With this approach, you just write a qmd with a code block that returns output "asis":

``````
```{python}
#| output: asis
#| echo: false

# this is a print statement, but imaging you used a loop to generate a card
# for each person, etc..
print("""
::: {.some-div}
:::
""")
```
``````

## Option 2: using a gallery with an ejs template

See the [Custom Listings page](https://quarto.org/docs/websites/website-listings-custom.html) on quarto.org. This is used in [quarto's website gallery](https://quarto.org/docs/gallery/) ([source code](https://github.com/quarto-dev/quarto-web/tree/main/docs/gallery)) and the [shiny gallery](https://shiny.posit.co/py/gallery/) ([source code](https://github.com/posit-dev/py-shiny-site/tree/main/gallery)) 

## Option 3: bail out and do it manually

We can always code it manually, but I suspect other parts of the site will benefit from this kind of workflow, so seems nice for us to get a feel for it!

### PR DESCRIPTION
**Pull request by rjake**
This PR uses R to create info cards and gallery of organizers. 

Closes #6

Netlify site:
https://pr-10--sjhphl.netlify.app/about.html

The organizer info is stored here:
https://github.com/socialjusticehackathon/website/blob/jake/assets/about--organizers.csv

image

image

## Todo:
- [ ] anchor sections not working
- [x] folder structure?
- [x] cards not mobile friendly
  - [x] try `::: {layout-ncol=2}`
  - [x] https://rstudio.github.io/bslib/articles/column-layout/index.html#responsive-number-of-columns
  - [x] Add in class like `:::: {.card .border-2 .rounded-3 .g-col-12 .g-col-md-12 .g-col-lg-4 .mb-2}` 
- [ ] style
  - [ ] use `color` instead of `opacity` in profile cards
  - [ ] update button color in `.btn { background-color: ? }`
- [x] update CSV with actual organizers
  - [ ] get correct images
- [x] confirm use of `div()` `p()` `tags$section()` etc. between `add_info_card()` and `add_profile_card()`

### CODE REVIEW

**Comment by travissouthard** [comment]
@ha0ye recommends this as possible card solution: https://rstudio.github.io/bslib/

**Comment by machow** [comment]
With bootstrap grid, you can add css classes that say how wide a item should be on different screen sizes.

E.g.: g-col-sm-12 means to be full width on a small screen:

* See this line in quartodoc: https://github.com/machow/quartodoc/blob/main/docs/examples/index.qmd#L24
* bootstrap docs: https://getbootstrap.com/docs/5.1/layout/css-grid/#three-columns

**Comment by ha0ye** [comment]
> anchor sections not working

I think this has to do with the page-layout being set to custom.

Solution 1. We could switch page-layout to `full` or `article`. This might change some of the spacing and other positioning of things.

Solution 2. We could also add `{.anchored}` after each heading and leave the page-layout as custom.

**Comment by travissouthard** [comment]
I asked the organizers to add their info to a copy of the CSV and can update this once I've gotten it confirmed done. I have also asked for photos, and can upload those as well.

**Comment by travissouthard** [comment]
@insiyahj suggested that it may make sense to just do a blurb for each person and skip the title column especially since we all are performing multiple roles in organizing this event

**Review by travissouthard — APPROVED** [review]
Sorry for the delay, but this looks great! Thank you for the good work!

**Pull request merged**
